
import React from 'react';

type LoadingStep = 'idle' | 'prompt' | 'image';

interface GeneratedImageDisplayProps {
  imageUrl: string | null;
  loadingStep: LoadingStep;
  error: string | null;
  promptGenerated: boolean;
}

export const GeneratedImageDisplay: React.FC<GeneratedImageDisplayProps> = ({
  imageUrl,
  loadingStep,
  error,
  promptGenerated,
}) => {
  const renderContent = () => {
    if (loadingStep === 'image') {
      return (
        <div className="flex flex-col items-center justify-center h-full text-slate-400">
          <div className="w-8 h-8 border-4 border-dashed rounded-full animate-spin border-teal-500"></div>
          <p className="mt-4 text-lg text-slate-500">Weaving pixels...</p>
        </div>
      );
    }

    if (error) {
      return (
        <div className="flex flex-col items-center justify-center h-full text-red-500/80 p-4">
          <p className="font-semibold text-center">Image Generation Failed</p>
          <p className="text-sm text-center mt-1">{error}</p>
        </div>
      );
    }
    
    if (imageUrl) {
      return (
        <img
          src={imageUrl}
          alt="Generated by AI"
          className="w-full h-full object-contain rounded-md animate-poof"
        />
      );
    }

    return (
      <div className="flex flex-col items-center justify-center h-full text-gray-600">
        <p className="text-lg">The conjured image will appear here.</p>
      </div>
    );
  };

  return (
    <div className="w-full h-full bg-black/30 border border-slate-800 rounded-lg p-4 relative flex items-center justify-center aspect-square lg:aspect-auto">
      {renderContent()}
    </div>
  );
};
